# Load configuration dicts
import pandas as pd
import yaml

# Import configuration files
params = yaml.load(open("config/params.yml", "r"), Loader=yaml.SafeLoader)
features = yaml.load(open("config/features.yml", "r"), Loader=yaml.SafeLoader)
samples = pd.read_table("config/samples.tsv", comment="#", dtype="str")

SAMPLE_LIBRARY = samples[["sample_id", "library_id"]].values.tolist()

REFERENCES = list(features["reference"].keys())


# Import subworkflows
include: "rules/folders.smk"
include: "rules/clean.smk"
include: "rules/helpers/__main__.smk"
include: "rules/reads/__main__.smk"
include: "rules/reference/__main__.smk"
include: "rules/preprocess/__main__.smk"


rule all:
    """
    Execute the entire pipeline
    """
    input:
        rules.reads.input,
        rules.reference.input,
        rules.preprocess.input,
