__use_yte__: true


default-resources:
    runtime: 1h
    mem_mb: 1G
    disk_mb: 1G

set-threads:
    preprocess__fastp__: 24

set-resources:
    preprocess__fastp__:
        time: 4h
        mem_mb: 8G
    preprocess__khmer__filter_low_abund__:
        time: 1d
        mem_mb: 8G
