__use_yte__: true


default-resources:
    runtime: 1h
    mem_mb: 1G
    disk_mb: 1G

set-threads:
    preprocess__fastp__: 24
    preprocess__khmer__interleave__: 2
    preprocess__khmer__trim_low_abund__: 8

set-resources:
    preprocess__fastp__:
        time: 4h
        mem_mb: 8G
    preprocess__khmer__interleave__:
        time: 6h
    preprocess__khmer__filter_low_abund__:
        time: 1d
        mem_mb: 8G
